### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by marcoaleixo** [tryolabs/luminoth#90] opened 2017-10-13 12:57 UTC
I created my virtual env with conda, everthing is working great but when I try access the server I receive the error:

```
Traceback (most recent call last)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/luminoth/tools/server/web.py", line 105, in index
return render_template('index.html')
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
return self._load_template(name, self.make_globals(globals))
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
template = self.loader.load(self, name, globals)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
source, filename, uptodate = self.get_source(environment, name)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
return self._get_source_fast(environment, template)
File "/home/marco/miniconda2/envs/DeepVision/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```

**Comment by vierja** [comment] 2017-10-13 13:32
I believe we screwed up the server in the 0.0.1 version. It should be fixed in master now. @gastonrod07 can you check?

**Comment by gastonrod07** [comment] 2017-10-13 14:14
I can't reproduce this error in both, master and the release tag. Have you modified the place of some files in the project?

**Comment by marcoaleixo** [comment] 2017-10-13 14:18
No, I used pip install luminoth and git clone https://github.com/tryolabs/luminoth.git in my directory.
Run lumi server web, started, the command show me the PIN but when I access I receive the error.

**Comment by dekked** [comment] 2017-10-16 21:03
@marcoaleixo can you try the following?

1. `pip uninstall luminoth` or create a new virtualenv.
2. `git clone https://github.com/tryolabs/luminoth.git` followed by `pip install -e .`
3. Try again to see if the server is working.

If it's still not working, let us know!

**Comment by dekked** [comment] 2017-10-27 13:12
@marcoaleixo did it finally work?

**Comment by marcoaleixo** [comment] 2017-10-30 20:44
Ops, sorry for the delayed response for some reason gmail does not notify me.
Yes, it finally work.
Thank you.

**Closed** 2017-10-31 17:43 UTC
