### ISSUE TITLE
multiple gpu issues

### ISSUE THREAD

**Issue by zzk88862** [tryolabs/luminoth#181] opened 2018-05-25 03:19 UTC
i have tried multiple gpu by with tf.device('/gpu:i'%i), but it always hits 已杀死， i have debugged many times, but it not solved! followings are some my run messages

1、nvdia messages
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111 Driver Version: 384.111 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 Tesla P4 Off | 00000000:81:00.0 Off | 0 |
| N/A 61C P0 24W / 75W | 4387MiB / 7606MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 Tesla P4 Off | 00000000:82:00.0 Off | 0 |
| N/A 62C P0 24W / 75W | 4881MiB / 7606MiB | 0% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| 0 24215 C /root/anaconda3/envs/new52/bin/python 4369MiB |
| 1 24215 C /root/anaconda3/envs/new52/bin/python 4863MiB |
+-----------------------------------------------------------------------------+

2、run result
![image](https://user-images.githubusercontent.com/31311358/40524514-74523d36-600d-11e8-8ca8-367ac116f2e6.png)

**Comment by dekked** [comment] 2018-08-11 23:31
Duplicate of #172.

**Closed by dekked** 2018-08-11 23:31 UTC
